# Generated by Django 3.2.25 on 2025-03-01 05:25

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20250228_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeimage',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to=core.models.recipe_image_file_path),
        ),
    ]
