# Generated by Django 3.2.25 on 2025-03-01 05:29

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_recipeimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to=core.models.recipe_image_file_path),
        ),
    ]
